prefix foursquare: <https://foursquare.com/> 
prefix owl: <http://www.w3.org/2002/07/owl#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix schema: <http://schema.org/> 
prefix tripadvisor: <http://tripadvisor.com> 
prefix xml: <http://www.w3.org/XML/1998/namespace> 
prefix xsd: <http://www.w3.org/2001/XMLSchema#> 
prefix yelp: <http://yelp.com/> 

select ?name ?venue {
  ?s a ?venue.
  ?s schema:name ?name
}

Group By ?name ?venue

limit 20